### ISSUE TITLE
Default download URL doesn't exist anymore

### ISSUE THREAD

**Issue by pablohildo** [BlueTeaLondon/heroku-buildpack-libreoffice-for-heroku-18#14]
Currently, the [default download URL](https://libreoffice.soluzioniopen.com/stable/fresh/LibreOffice-fresh.basic-x86_64.AppImage) doesn't exist. It looks like a new strategy should be decided, since there is no fresh basic url anymore. 
I'd suggest simply using the latest version (7.0.3), as anyone who desires to use a different version can simply do so through `LibreOfficeAppImage`.

Once we discuss this, I'd be happy to work on it.

**Comment by geomic** [comment]
@pablohildo I just took a look - could they just have changed the placement of images? E.g. take a look here: https://libreoffice.soluzioniopen.com/stable/

Although the `fresh` folder doesn't include a "latest" file, the `standard` folder does seem to include a `fresh` image. There is a difference in the size (and therefore likely version) but if you are up for a quick verification (that the buildback still works with the image from the new fixed fresh URL) it could be changed to that?

**Comment by pablohildo** [comment]
It sure seems likely. I will give it a try in some minutes and will give feedback soon!

**Comment by pablohildo** [comment]
Just tested it, can confirm everything works well. I'll be opening a PR pretty soon
