### ISSUE TITLE
Error converting file 

### ISSUE THREAD

**Issue by Daved-Andreh** [BlueTeaLondon/heroku-buildpack-libreoffice-for-heroku-18#20]
I am receiving the following error :
Error converting file: Error: Could not find soffice binary

heroku run soffice --version returns the version but I still get the error.

Any idea why?

**Comment by geomic** [comment]
Hi @DavedAndreh-learnaholiks, did you manage to resolve this?

**Comment by Daved-Andreh** [comment]
Hello,

I changed the library I was using in order to make it work.

Thank you

**Comment by geomic** [comment]
@DavedAndreh-learnaholiks thanks for this. So, to confirm, the issue isn't resolved within the build pack itself? If so, I'd like to reopen to track resolution.
