### ISSUE TITLE
SSL certificate of mirror domain expired 

### ISSUE THREAD

**Issue by alexandre-paroissien** [BlueTeaLondon/heroku-buildpack-libreoffice-for-heroku-18#8]
Hello,
It seems that the SSL certificate of the domain soluzioniopen.com expired today
I am not sure where to report the issue, I posted there:
https://github.com/antoniofaccioli/libreoffice-appimage/issues/15
He seems to be the owner of the domain
Do you have any other mirrors?
Thanks

**Comment by vesatoivonen** [comment]
One option is to host your own and set the url for the AppImage with `LibreOfficeAppImage` as instructed in the readme.
Otherwise I'd expect the certificate to be renewed within days.

**Comment by alexandre-paroissien** [comment]
Ok thanks for the quick reply, I'll try that!

**Comment by alexandre-paroissien** [comment]
Seems fixed with new certificate valid from June 12 to Sept 10
